files:
  include: 'app/**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  # Extends
  extends-before-declarations: 0
  extends-before-mixins: 0

  # Mixins
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
  mixins-before-declarations: 0

  # Disallow
  no-color-keywords: 0
  no-duplicate-properties: 1
  no-ids: 0
  no-important: 0
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties:
        - justify-items
  no-qualifying-elements: 0
  no-trailing-zero: 0
  no-transition-all: 1
  no-url-protocols: 0
  no-vendor-prefixes: 0

  # Nesting
  force-attribute-nesting: 1
  force-element-nesting: 0
  force-pseudo-nesting: 0
  nesting-depth:
    - 1
    - max-depth: 6

  # Name Formats
  class-name-format:
    - 0
    - convention: hyphenatedlowercase
  function-name-format:
    - 1
    - convention: hyphenatedlowercase
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
  variable-name-format:
    - 0
    - convention: hyphenatedlowercase

  # Style Guide
  indentation:
    - 1
    - size: 2
  property-sort-order:
    - 1
    - ignore-custom-properties: false
      order:
        - tart
        - '-webkit-animation'
        - '-moz-animation'
        - '-ms-animation'
        - '-o-animation'
        - animation
        - '-webkit-animation-delay'
        - '-moz-animation-delay'
        - '-ms-animation-delay'
        - '-o-animation-delay'
        - animation-delay
        - '-webkit-animation-direction'
        - '-moz-animation-direction'
        - '-ms-animation-direction'
        - '-o-animation-direction'
        - animation-direction
        - '-webkit-animation-duration'
        - '-moz-animation-duration'
        - '-ms-animation-duration'
        - '-o-animation-duration'
        - animation-duration
        - '-webkit-animation-iteration-count'
        - '-moz-animation-iteration-count'
        - '-ms-animation-iteration-count'
        - '-o-animation-iteration-count'
        - animation-iteration-count
        - '-webkit-animation-name'
        - '-moz-animation-name'
        - '-ms-animation-name'
        - '-o-animation-name'
        - animation-name
        - '-webkit-animation-play-state'
        - '-moz-animation-play-state'
        - '-ms-animation-play-state'
        - '-o-animation-play-state'
        - animation-play-state
        - '-webkit-animation-timing-function'
        - '-moz-animation-timing-function'
        - '-ms-animation-timing-function'
        - '-o-animation-timing-function'
        - animation-timing-function
        - align-content
        - align-items
        - align-self
        - '-webkit-backface-visibility'
        - backface-visibility
        - background
        - background-attachment
        - background-clip
        - background-color
        - background-image
        - background-origin
        - background-position
        - '-ms-background-position-x'
        - background-position-x
        - '-ms-background-position-y'
        - background-position-y
        - background-repeat
        - background-size
        - border
        - border-bottom
        - border-bottom-color
        - '-webkit-border-bottom-image'
        - '-moz-border-bottom-image'
        - '-o-border-bottom-image'
        - border-bottom-image
        - '-webkit-border-bottom-left-image'
        - '-moz-border-bottom-left-image'
        - '-o-border-bottom-left-image'
        - border-bottom-left-image
        - '-webkit-border-bottom-left-radius'
        - '-moz-border-bottom-left-radius'
        - border-bottom-left-radius
        - '-webkit-border-bottom-right-image'
        - '-moz-border-bottom-right-image'
        - '-o-border-bottom-right-image'
        - border-bottom-right-image
        - '-webkit-border-bottom-right-radius'
        - '-moz-border-bottom-right-radius'
        - border-bottom-right-radius
        - border-bottom-style
        - border-bottom-width
        - border-collapse
        - border-color
        - '-webkit-border-corner-image'
        - '-moz-border-corner-image'
        - '-o-border-corner-image'
        - border-corner-image
        - '-webkit-border-image'
        - '-moz-border-image'
        - '-o-border-image'
        - border-image
        - '-webkit-border-image-outset'
        - '-moz-border-image-outset'
        - '-o-border-image-outset'
        - border-image-outset
        - '-webkit-border-image-repeat'
        - '-moz-border-image-repeat'
        - '-o-border-image-repeat'
        - border-image-repeat
        - '-webkit-border-image-slice'
        - '-moz-border-image-slice'
        - '-o-border-image-slice'
        - border-image-slice
        - '-webkit-border-image-source'
        - '-moz-border-image-source'
        - '-o-border-image-source'
        - border-image-source
        - '-webkit-border-image-width'
        - '-moz-border-image-width'
        - '-o-border-image-width'
        - border-image-width
        - border-left
        - border-left-color
        - '-webkit-border-left-image'
        - '-moz-border-left-image'
        - '-o-border-left-image'
        - border-left-image
        - border-left-style
        - border-left-width
        - '-webkit-border-radius'
        - '-moz-border-radius'
        - border-radius
        - border-right
        - border-right-color
        - '-webkit-border-right-image'
        - '-moz-border-right-image'
        - '-o-border-right-image'
        - border-right-image
        - border-right-style
        - border-right-width
        - border-spacing
        - border-style
        - border-top
        - border-top-color
        - '-webkit-border-top-image'
        - '-moz-border-top-image'
        - '-o-border-top-image'
        - border-top-image
        - '-webkit-border-top-left-image'
        - '-moz-border-top-left-image'
        - '-o-border-top-left-image'
        - border-top-left-image
        - '-webkit-border-top-left-radius'
        - '-moz-border-top-left-radius'
        - border-top-left-radius
        - '-webkit-border-top-right-image'
        - '-moz-border-top-right-image'
        - '-o-border-top-right-image'
        - border-top-right-image
        - '-webkit-border-top-right-radius'
        - '-moz-border-top-right-radius'
        - border-top-right-radius
        - border-top-style
        - border-top-width
        - border-width
        - bottom
        - box-decoration-break
        - '-webkit-box-shadow'
        - '-moz-box-shadow'
        - box-shadow
        - '-webkit-box-sizing'
        - '-moz-box-sizing'
        - box-sizing
        - break-after
        - break-before
        - break-inside
        - caption-side
        - clear
        - clip
        - color
        - '-webkit-column-count'
        - '-moz-column-count'
        - column-count
        - '-webkit-column-fill'
        - '-moz-column-fill'
        - column-fill
        - '-webkit-column-gap'
        - '-moz-column-gap'
        - column-gap
        - '-webkit-column-rule'
        - '-moz-column-rule'
        - column-rule
        - '-webkit-column-rule-color'
        - '-moz-column-rule-color'
        - column-rule-color
        - '-webkit-column-rule-style'
        - '-moz-column-rule-style'
        - column-rule-style
        - '-webkit-column-rule-width'
        - '-moz-column-rule-width'
        - column-rule-width
        - '-webkit-column-span'
        - '-moz-column-span'
        - column-span
        - '-webkit-column-width'
        - '-moz-column-width'
        - column-width
        - '-webkit-columns'
        - '-moz-columns'
        - columns
        - content
        - counter-increment
        - counter-reset
        - cursor
        - direction
        - display
        - empty-cells
        - 'filter:progid:DXImageTransform.Microsoft.AlphaImageLoader'
        - 'filter:progid:DXImageTransform.Microsoft.Alpha(Opacity'
        - '-ms-interpolation-mode'
        - '-webkit-filter'
        - '-ms-filter'
        - filter
        - '-webkit-flex-align'
        - '-moz-flex-align'
        - '-ms-flex-align'
        - '-o-flex-align'
        - flex-align
        - '-webkit-flex'
        - '-moz-flex'
        - '-ms-flex'
        - '-o-flex'
        - flex
        - '-webkit-flex-basis'
        - '-moz-flex-basis'
        - '-ms-flex-basis'
        - '-o-flex-basis'
        - flex-basis
        - '-webkit-flex-direction'
        - '-moz-flex-direction'
        - '-ms-flex-direction'
        - '-o-flex-direction'
        - flex-direction
        - '-webkit-flex-order'
        - '-moz-flex-order'
        - '-ms-flex-order'
        - '-o-flex-order'
        - flex-flow
        - '-webkit-flex-flow'
        - '-moz-flex-flow'
        - '-ms-flex-flow'
        - '-o-flex-flow'
        - flex-grow
        - '-webkit-flex-grow'
        - '-moz-flex-grow'
        - '-ms-flex-grow'
        - '-o-flex-grow'
        - flex-order
        - '-webkit-flex-pack'
        - '-moz-flex-pack'
        - '-ms-flex-pack'
        - '-o-flex-pack'
        - flex-pack
        - '-webkit-flex-wrap'
        - '-moz-flex-wrap'
        - '-ms-flex-wrap'
        - '-o-flex-wrap'
        - flex-wrap
        - float
        - font
        - font-family
        - '-moz-osx-font-smoothing'
        - '-webkit-font-smoothing'
        - font-smoothing
        - font-size
        - font-size-adjust
        - font-stretch
        - font-style
        - font-variant
        - font-weight
        - height
        - '-webkit-hyphens'
        - '-moz-hyphens'
        - hyphens
        - image-rendering
        - justify-content
        - justify-items
        - justify-self
        - left
        - letter-spacing
        - line-height
        - list-style
        - list-style-image
        - list-style-position
        - list-style-type
        - margin
        - margin-bottom
        - margin-left
        - margin-right
        - margin-top
        - max-height
        - max-width
        - max-zoom
        - min-height
        - min-width
        - min-zoom
        - nav-down
        - nav-index
        - nav-left
        - nav-right
        - nav-up
        - opacity
        - orientation
        - orphans
        - outline
        - outline-color
        - outline-offset
        - outline-style
        - outline-width
        - overflow
        - '-ms-overflow-x'
        - '-ms-overflow-y'
        - overflow-x
        - overflow-y
        - padding
        - padding-bottom
        - padding-left
        - padding-right
        - padding-top
        - page-break-after
        - page-break-before
        - page-break-inside
        - perspective
        - pointer-events
        - position
        - quotes
        - resize
        - right
        - src
        - '-moz-tab-size'
        - '-o-tab-size'
        - tab-size
        - table-layout
        - text-align
        - '-ms-text-align-last'
        - text-align-last
        - text-decoration
        - text-emphasis
        - text-emphasis-color
        - text-emphasis-position
        - text-emphasis-style
        - text-indent
        - '-ms-text-justify'
        - text-justify
        - text-outline
        - '-ms-text-overflow'
        - text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - text-shadow
        - text-transform
        - text-wrap
        - top
        - '-webkit-transform'
        - '-moz-transform'
        - '-ms-transform'
        - '-o-transform'
        - transform
        - '-webkit-transform-origin'
        - '-moz-transform-origin'
        - '-ms-transform-origin'
        - '-o-transform-origin'
        - transform-origin
        - '-webkit-transition'
        - '-moz-transition'
        - '-ms-transition'
        - '-o-transition'
        - transition
        - '-webkit-transition-delay'
        - '-moz-transition-delay'
        - '-ms-transition-delay'
        - '-o-transition-delay'
        - transition-delay
        - '-webkit-transition-duration'
        - '-moz-transition-duration'
        - '-ms-transition-duration'
        - '-o-transition-duration'
        - transition-duration
        - '-webkit-transition-property'
        - '-moz-transition-property'
        - '-ms-transition-property'
        - '-o-transition-property'
        - transition-property
        - '-webkit-transition-timing-function'
        - '-moz-transition-timing-function'
        - '-ms-transition-timing-function'
        - '-o-transition-timing-function'
        - transition-timing-function
        - unicode-bidi
        - user-zoom
        - vertical-align
        - visibility
        - white-space
        - widows
        - width
        - '-ms-writing-mode'
        - '-ms-word-break'
        - word-break
        - word-spacing
        - '-ms-word-wrap'
        - word-wrap
        - z-index
        - '-ms-zoom'
        - zoom
  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
        - 4
  space-after-colon: 1
  trailing-semicolon: 0
  url-quotes: 0
